# -*- coding: utf-8 -*-
"""Soulbound v0.50.0 runtime manifest.

The file order is explicit because legacy gameplay modules still share one
runtime API. v0.47.0 keeps legacy compatibility while allowing reviewed modules to run with
fully explicit imports and declared exports while preserving the reviewed historical
load order and rejecting accidental overrides.
"""

RUNTIME_MODULES = ['core/bootstrap_economy_professions.py',
 'core/progression_resources.py',
 'core/progression_600.py',
 'core/classes_skills.py',
 'core/command_catalog.py',
 'core/mines_threat.py',
 'systems/items_resources.py',
 'systems/equipment_crafting.py',
 'systems/content_registry.py',
 'systems/dungeons_regions.py',
 'world/expansions.py',
 'world/machine_expansion.py',
 'world/magitek_dungeon.py',
 'systems/tech_crafting.py',
 'world/equipment_help.py',
 'world/economy_quests.py',
 'world/dynamic_content.py',
 'network/protocol_gameplay_utils.py',
 'network/tech_runes.py',
 'systems/crafting_expansion.py',
 'systems/milestone.py',
 'storage/schema_core.py',
 'storage/schema_progression.py',
 'storage/schema_world_quests.py',
 'storage/schema_social_guilds.py',
 'storage/schema_migrate_social.py',
 'storage/schema_migrate_character.py',
 'storage/schema_migrate_guilds.py',
 'storage/schema_migrate_tools.py',
 'storage/schema_migrate_economy.py',
 'storage/schema_migrate_history.py',
 'storage/db_schema.py',
 'storage/db_accounts.py',
 'storage/db_world.py',
 'storage/db_inventory.py',
 'storage/db_progression.py',
 'storage/db_quests.py',
 'storage/db_guilds.py',
 'storage/database.py',
 'storage/db_crafting_extensions.py',
 'player/character.py',
 'world/generation_systems.py',
 'world/world_expansion_i.py',
 'world/world_expansion_ii.py',
 'world/runtime_progression.py',
 'world/living_npcs.py',
 'world/world_state.py',
 'systems/professions.py',
 'systems/crafting_quality.py',
 'player/session_mixins/session_runtime_state.py',
 'player/session_mixins/dungeon_progression.py',
 'player/session_mixins/rest_mana.py',
 'player/session_mixins/class_progression.py',
 'player/session_mixins/core_progression.py',
 'player/session_mixins/io_auth_character.py',
 'player/session_mixins/equipment_stats.py',
 'player/session_mixins/perception_maps.py',
 'player/session_mixins/museum_bounty.py',
 'player/session_mixins/world_events_endgame.py',
 'player/session_mixins/exploration_progress.py',
 'player/session_mixins/collection_loot_records.py',
 'player/session_mixins/world_progression.py',
 'player/session_mixins/progress_titles.py',
 'player/session_mixins/progress_gaps.py',
 'player/session_mixins/crafting_orders.py',
 'player/session_mixins/equipment_compare.py',
 'player/session_mixins/item_sources.py',
 'player/session_mixins/help_system.py',
 'player/session_mixins/atlas_codex.py',
 'player/session_mixins/character_profile.py',
 'player/session_mixins/class_guild_progress.py',
 'player/session_mixins/help_codex_profile.py',
 'player/session_mixins/movement.py',
 'player/session_mixins/party.py',
 'player/session_mixins/exp_terrain.py',
 'player/session_mixins/social_base.py',
 'player/session_mixins/banking_charisma.py',
 'player/session_mixins/movement_party_social.py',
 'player/session_mixins/profession_storage.py',
 'player/session_mixins/guide_navigation.py',
 'player/session_mixins/gathering.py',
 'player/session_mixins/professions_storage_guide.py',
 'player/session_mixins/admin_tools.py',
 'player/session_mixins/gathering_actions.py',
 'player/session_mixins/sales.py',
 'player/session_mixins/admin_gathering_sales.py',
 'player/session_mixins/crafting.py',
 'player/session_mixins/inventory_equipment.py',
 'player/session_mixins/shops_teachers.py',
 'player/session_mixins/crafting_inventory_equipment.py',
 'player/session_mixins/quest_progress.py',
 'player/session_mixins/quest_offers.py',
 'player/session_mixins/quest_turnin.py',
 'player/session_mixins/quest_npc.py',
 'player/session_mixins/quest_commands.py',
 'player/session_mixins/quests.py',
 'player/session_mixins/skill_learning.py',
 'player/session_mixins/skill_queue_buffs.py',
 'player/session_mixins/combat_skills.py',
 'player/session_mixins/combat_damage.py',
 'player/session_mixins/combat_realtime.py',
 'player/session_mixins/combat_rewards.py',
 'player/session_mixins/combat_survival.py',
 'player/session_mixins/combat.py',
 'player/session_mixins/skills_combat.py',
 'player/session_mixins/forge_guilds.py',
 'player/session_mixins/mail_attachments.py',
 'player/session_mixins/social_expansion.py',
 'player/session_mixins/courier_delivery.py',
 'player/session_mixins/progression_accessibility.py',
 'player/session_mixins/professions.py',
 'player/session_mixins/tech_crafting.py',
 'player/session_mixins/crafting_expansion.py',
 'player/session_mixins/milestone.py',
 'player/session_mixins/command_special_handlers.py',
 'player/session_mixins/activity_guidance.py',
 'player/session_mixins/command_registry.py',
 'player/session_mixins/command_loop.py',
 'player/session.py',
 'server/mud_server.py',
 'admin/help_refresh.py',
 'admin/audits.py',
 'systems/economy_audit_v03060.py',
 'systems/full_systems_audit_v03062.py',
 'admin/crafting_audit_v03114.py',
 'world/uoss_superbosses.py',
 'world/crypt_party_rebalance.py',
 'world/crypt_floor_progression.py',
 'world/crypt_overdrive.py',
 'world/tower_overdrive.py',
 'world/magitek_infinite.py',
 'world/magitek_hourly_quests.py',
 'world/world_threat_overdrive.py',
 'world/troll_shaman_density.py',
 'systems/public_records.py',
 'admin/party_revive_audit_v0371.py',
 'world/party_combo_ultimate_summary.py',
 'systems/currency_ratio.py',
 'world/global_difficulty_overdrive.py',
 'admin/bounty_target_audit_v0387.py',
 'admin/soul_tier8_trial_audit_v0388.py',
 'admin/quest_kill_credit_audit_v0389.py',
 'systems/smithing_materials.py',
 'systems/server_chronicle.py',
 'systems/dungeon_entry_commands.py',
 'admin/bounty_abandon_audit_v03814.py',
 'admin/architecture_audit_v0390.py',
 'admin/maintenance_audit_v0400.py',
 'admin/native_modules_audit_v0410.py',
 'admin/modular_services_audit_v0420.py',
 'admin/explicit_dependencies_audit_v0430.py',
 'admin/explicit_gameplay_dependencies_audit_v0440.py',
 'admin/explicit_stable_dependencies_audit_v0450.py',
 'admin/explicit_persistence_audit_v0460.py',
 'admin/combat_architecture_audit_v0470.py',
 'admin/catalog_ownership_audit_v0480.py',
 'admin/command_registry_audit_v0490.py',
 'admin/maintainable_core_audit_v0500.py',
 'admin/progression_pace_audit_v0501.py',
 'admin/long_term_balance_audit_v0502.py',
 'admin/world_expansion_i_audit_v0510.py',
 'admin/world_expansion_ii_audit_v0520.py',
 'admin/railway_packaging_audit_v0521.py',
 'admin/postal_quest_rewards_audit_v0522.py',
 'admin/courier_guild_audit_v0530.py',
 'admin/courier_achievements_audit_v0540.py',
 'admin/courier_prestige_tavern_audit_v0550.py',
 'world/living_npcs_finalize.py',
 'admin/living_npcs_activity_audit_v0560.py',
 'admin/living_npcs_late_finalize_audit_v0581.py',
 'admin/modular_refactor_audit_v0570.py',
 'admin/titles_progress_audit_v0580.py',
 'admin/crafting_orders_compare_audit_v0600.py',
 'admin/item_sources_party_coordination_audit_v0610.py',
 'admin/crafting_logistics_audit_v0614.py',
 'systems/runtime_memory.py',
 'admin/release_integrity_v0369.py']


# v0.43.0+: modules in this map are NOT seeded with the compatibility runtime
# namespace and are NOT synchronized with late-bound globals.  They must use
# ordinary Python imports.  Only the declared exports are published back to
# the compatibility runtime for older downstream modules.
EXPLICIT_RUNTIME_EXPORTS = {
    "storage/database.py": ("Database",),
    "player/session_mixins/command_registry.py": (
        "COMMAND_TEXT", "COMMAND_NAME", "COMMAND_REGISTRY",
        "DOWNED_SAFE_COMMANDS", "REST_SAFE_COMMANDS", "GUIDE_SAFE_COMMANDS",
        "resolve_session_command", "command_state_safe", "SessionCommandRegistryMixin",
    ),
    "player/session_mixins/core_progression.py": ("SessionCoreProgressionMixin",),
    "player/session_mixins/world_progression.py": ("SessionWorldProgressionMixin",),
    "player/session_mixins/help_codex_profile.py": ("SessionHelpCodexProfileMixin",),
    "player/session_mixins/movement_party_social.py": ("SessionMovementPartySocialMixin",),
    "player/session_mixins/professions_storage_guide.py": ("SessionProfessionsStorageGuideMixin",),
    "player/session_mixins/admin_gathering_sales.py": ("SessionAdminGatheringSalesMixin",),
    "player/session_mixins/crafting_inventory_equipment.py": ("SessionCraftingInventoryEquipmentMixin",),
    "player/session_mixins/quests.py": ("SessionQuestsMixin",),
    "player/session_mixins/skills_combat.py": (
        "party_drop_recipients_v0359", "SessionSkillsCombatMixin",
    ),
    "player/session.py": ("Session",),
    "admin/modular_services_audit_v0420.py": (
        "modular_services_audit_v0420", "MODULAR_SERVICES_AUDIT_V0420",
    ),
    "admin/explicit_dependencies_audit_v0430.py": (
        "explicit_dependencies_audit_v0430", "EXPLICIT_DEPENDENCIES_AUDIT_V0430",
    ),
}


# v0.44.0: second migration wave — gameplay modules with stable dependency
# graphs now use ordinary imports and declared compatibility exports.
V044_EXPLICIT_RUNTIME_EXPORTS = {'systems/equipment_crafting.py': ('ALCHEMY_RECIPES',
                                   'CLASS_SET_BONUSES',
                                   'CLASS_SET_STAT_NAMES',
                                   'COOK_RECIPES',
                                   'CRAFT_RECIPES',
                                   'CUT_GEM_IDS',
                                   'GEM_AFFIX_NAMES',
                                   'GEM_DEFINITIONS',
                                   'GEM_QUALITY_INFO',
                                   'GEM_QUALITY_ORDER',
                                   'GEODE_DEFINITIONS',
                                   'GEODE_IDS',
                                   'GUILD_BOUNTY_TARGETS',
                                   'GUILD_CLASS_QUESTS',
                                   'GUILD_EXAM_REPUTATION',
                                   'GUILD_EXAM_THRESHOLDS',
                                   'GUILD_REPUTATION_MAX',
                                   'GUILD_REPUTATION_RANKS',
                                   'JEWELCRAFTING_TIERS',
                                   'JEWELCRAFT_RECIPES',
                                   'LEGENDARY_CLASS_LOOT_TIERS',
                                   'LEGENDARY_CLASS_RELIC_BY_CLASS_TIER',
                                   'LEGENDARY_CLASS_SET_ITEMS_BY_CLASS_TIER',
                                   'MINING_STORAGE_IDS',
                                   'RAW_GEM_IDS',
                                   'RIVER_FISH_COOKING_IDS',
                                   'SHOPS',
                                   'SHOP_SELLERS',
                                   '_class_equipment_rarity_name',
                                   '_class_equipment_tier_label',
                                   '_legendary_class_loot_stat_profile',
                                   '_register_blacksmith_recipes',
                                   '_register_class_equipment_shops',
                                   '_register_gem_quality_variants',
                                   '_register_gem_system',
                                   '_register_jewelcrafting_recipes',
                                   '_register_legendary_class_loot',
                                   'class_equipment_base_stat_pair',
                                   'class_equipment_base_stats_text',
                                   'class_equipment_profile',
                                   'class_equipment_profile_properties',
                                   'class_equipment_split_stat_budget',
                                   'class_equipment_stat_budget',
                                   'class_equipment_unlocked_tier',
                                   'gem_definition_by_cut_id',
                                   'gem_definition_by_raw_id',
                                   'gem_quality_amount',
                                   'gem_quality_item_id',
                                   'jewelry_socket_capacity',
                                   'roll_mined_gem_quality',
                                   'roll_mining_geode'),
 'systems/dungeons_regions.py': ('ASTRAL_BOSS_FLOORS',
                                 'ASTRAL_BOSS_MECHANICS',
                                 'ASTRAL_BOSS_MECHANIC_TEXT',
                                 'ASTRAL_BOSS_NAMES',
                                 'ASTRAL_BOSS_RELICS',
                                 'ASTRAL_MAX_FLOOR',
                                 'ASTRAL_MIN_FLOOR',
                                 'ASTRAL_MIN_SOUL_LEVEL',
                                 'ASTRAL_REGULAR_NAMES',
                                 'BOSS_RELICS',
                                 'CRYPT_AFFIXES',
                                 'CRYPT_BOSS_MECHANICS',
                                 'CRYPT_BOSS_MECHANIC_TEXT',
                                 'CRYPT_BOSS_NAMES',
                                 'CRYPT_RARITIES',
                                 'CRYPT_REGULAR_NAMES',
                                 'CRYPT_TRIAL_TARGETS',
                                 'ELITE_AFFIXES',
                                 'FIELD_RESOURCE_MIN_TOOL_LEVEL',
                                 'GIANT_FORTRESS_BOSS_FLOORS',
                                 'GIANT_FORTRESS_BOSS_MECHANICS',
                                 'GIANT_FORTRESS_BOSS_NAMES',
                                 'GIANT_FORTRESS_MAX_FLOOR',
                                 'HERB_SPECIFIC_MEADOWS',
                                 'HERB_SPECIFIC_MEADOW_MIN_TOOL_LEVEL',
                                 'HERB_SPECIFIC_MEADOW_NAMES',
                                 'MYTHIC_ASTRAL_MIN_SOUL_LEVEL',
                                 'MYTHIC_ASTRAL_REGULAR_NAMES',
                                 'MYTHIC_BOSS_FLOORS',
                                 'MYTHIC_CRYPT_MIN_SOUL_LEVEL',
                                 'MYTHIC_CRYPT_REGULAR_NAMES',
                                 'MYTHIC_MAX_FLOOR',
                                 'MYTHIC_MIN_FLOOR',
                                 'PROF_DUNGEON_COMBAT_NAMES',
                                 'PROF_DUNGEON_MAX_FLOOR',
                                 'PROF_DUNGEON_PREFIXES',
                                 'PROF_DUNGEON_TOOL',
                                 'RARE_TROLL_VARIANTS',
                                 'V0866_ELITE_MOB_SPAWN_CHANCE',
                                 'V0866_RARE_MOB_SPAWN_CHANCE',
                                 'V0866_RARE_TROLL_SPAWN_CHANCE',
                                 'WORLD_BOSS_UNIQUES',
                                 '_register_elite_variants',
                                 '_register_rare_variants',
                                 'astral_floor_id',
                                 'astral_floor_number',
                                 'build_astral_tower',
                                 'build_crypt_200_floors',
                                 'build_crypt_loot_variants',
                                 'build_mountain_region_and_herb_meadows',
                                 'build_mythic_endgame',
                                 'build_profession_dungeons',
                                 'crypt_affix_amount',
                                 'crypt_depth_multiplier',
                                 'crypt_depth_step',
                                 'crypt_floor_id',
                                 'crypt_floor_number',
                                 'crypt_variant_id',
                                 'giant_fortress_floor_id',
                                 'giant_fortress_floor_number',
                                 'is_astral_boss_floor',
                                 'is_crypt_boss_floor',
                                 'is_giant_fortress_boss_floor',
                                 'is_mythic_astral_boss_floor',
                                 'is_mythic_crypt_boss_floor',
                                 'mythic_astral_floor_id',
                                 'mythic_astral_floor_number',
                                 'mythic_crypt_floor_id',
                                 'mythic_crypt_floor_number',
                                 'profession_dungeon_combat_pack',
                                 'profession_dungeon_floor',
                                 'profession_dungeon_required_tool_level',
                                 'profession_dungeon_room_id',
                                 'resolve_world_spawn_template',
                                 'roll_crypt_loot_item',
                                 'roll_crypt_rarity'),
 'world/equipment_help.py': ('CLASS_DROP_MASTERY_BY_MATERIAL',
                             'DENSE_DUNGEON_ADDED_SPAWNS',
                             'DENSE_DUNGEON_ZONES',
                             'DENSE_ZONE_NAME_POOLS',
                             'EQUIPMENT_MASTERY_LEVELS_V0919',
                             'V0861_BASE_SHOP_PRICES_SILVER',
                             'V0861_CLASS_SLOT_PRICE_FACTOR',
                             'V0861_CLASS_TIER_BASE_SILVER',
                             'V0918_EQUIPMENT_MASTERY_CONFIGURED',
                             'V0919_EQUIPMENT_BY_LEVEL_SLOT',
                             'V0919_INVALID_EQUIPMENT_THRESHOLDS',
                             'V0919_NORMALIZED_EQUIPMENT_REQUIREMENTS',
                             '_add_profession_400_quest',
                             '_corpse_material_tier_by_index',
                             '_dungeon_material_tier_index',
                             '_is_boss_for_density',
                             '_is_equipment_progression_boss',
                             'class_equipment_drop_chance',
                             'class_equipment_drop_mastery_for_template',
                             'class_equipment_drop_pool',
                             'configure_base_mob_corpse_equipment',
                             'configure_equipment_mastery_requirements_v0918',
                             'configure_material_corpse_equipment',
                             'configure_soul_trials_v0261',
                             'configure_v0856_help_categories',
                             'configure_v0856_help_refresh',
                             'configure_v0856_walking_help',
                             'configure_v0857_navigation_help',
                             'configure_v0917_help',
                             'corpse_material_tier_for_mastery_v0919',
                             'corpse_material_tier_for_template',
                             'densify_static_dungeon_spawns',
                             'equipment_progression_mastery_for_template_v0919',
                             'normalize_all_equipment_mastery_v0919',
                             'normalize_equipment_mastery_v0919',
                             'v0251_enforce_single_mine',
                             'v0919_equipment_progression_audit'),
 'storage/db_schema.py': ('DatabaseSchemaMixin',),
 'player/character.py': ('Character', 'GLOBAL_MOB_AUTO_AGGRO_ENABLED'),
 'player/session_mixins/dungeon_progression.py': ('SessionDungeonProgressionMixin',),
 'player/session_mixins/io_auth_character.py': ('SessionIOAuthCharacterMixin', 'time'),
 'player/session_mixins/equipment_stats.py': ('SessionEquipmentStatsMixin', 'moogle_board_stat_bonus_v0313'),
 'player/session_mixins/museum_bounty.py': ('SessionMuseumBountyMixin',),
 'player/session_mixins/exploration_progress.py': ('SessionExplorationProgressMixin',),
 'player/session_mixins/character_profile.py': ('SessionCharacterProfileMixin',),
 'player/session_mixins/movement.py': ('SessionMovementMixin',),
 'player/session_mixins/exp_terrain.py': ('SessionExpTerrainMixin',),
 'player/session_mixins/banking_charisma.py': ('SessionBankingCharismaMixin',),
 'player/session_mixins/profession_storage.py': ('SessionProfessionStorageMixin',),
 'player/session_mixins/guide_navigation.py': ('SessionGuideNavigationMixin',),
 'player/session_mixins/gathering.py': ('SessionGatheringMixin',),
 'player/session_mixins/gathering_actions.py': ('ResourceGatheredEvent', 'SessionGatheringActionsMixin'),
 'player/session_mixins/sales.py': ('SessionSalesMixin',),
 'player/session_mixins/crafting.py': ('SessionCraftingMixin',),
 'player/session_mixins/inventory_equipment.py': ('SessionInventoryEquipmentMixin',),
 'player/session_mixins/shops_teachers.py': ('SessionShopsTeachersMixin',),
 'player/session_mixins/quest_npc.py': ('SessionQuestNpcMixin',),
 'player/session_mixins/skill_learning.py': ('SessionSkillLearningMixin',),
 'player/session_mixins/professions.py': ('SessionProfessionsV03053Mixin',),
 'player/session_mixins/crafting_expansion.py': ('SessionCraftingExpansionV03114Mixin',)}
EXPLICIT_RUNTIME_EXPORTS.update(V044_EXPLICIT_RUNTIME_EXPORTS)
EXPLICIT_RUNTIME_EXPORTS["admin/explicit_gameplay_dependencies_audit_v0440.py"] = (
    "explicit_gameplay_dependencies_audit_v0440",
    "EXPLICIT_GAMEPLAY_DEPENDENCIES_AUDIT_V0440",
)


# v0.45.0: conservative third migration wave. Only modules whose late-bound
# behaviour was proven stable are moved out of the compatibility bridge.
V045_EXPLICIT_RUNTIME_EXPORTS = {'admin/crafting_audit_v03114.py': ('FULL_CRAFTING_AUDIT_V03114', 'full_crafting_audit_v03114'),
 'core/classes_skills.py': ('AREA_MAGIC_AND_GROUP_HEALING_SKILLS',
                            'CLASSES',
                            'CLASS_DESCRIPTIONS',
                            'CLASS_SKILLS',
                            'CLASS_STARTING_STAT_BONUSES',
                            'ENDGAME_CLASS_SKILLS',
                            'HERB_ATLAS_ROOM_MIN_LEVELS',
                            'NATURAL_SKILL_INTENTS',
                            'ORE_ATLAS_LEVELS',
                            'ORE_MINE_FLOOR_MINIMUMS',
                            'RACES',
                            'RACE_CLASS_RECOMMENDATIONS',
                            'ROOMS',
                            'SOUL_LEVEL_SKILL_EXPANSION',
                            'SOUL_SKILL_UNLOCK_LEVELS',
                            'SOUL_WEAPON_ATTACK_TECHNIQUES',
                            'V03014_OLD_NAME_ALIASES',
                            'V03014_SKILLS_RENAMED',
                            'V03014_SKILL_NAME_AUDIT_PREGEN',
                            'V0876_CLASS_STARTING_STAT_BONUSES',
                            'V0876_RACE_BASE_STATS',
                            'WOOD_ATLAS_ROOM_MIN_LEVELS',
                            '_POST200_CLASS_NOUN',
                            '_POST200_ROLE_KINDS',
                            '_POST200_SKILL_STAGES',
                            '_SOUL_GRID_CLASS_PROFILES',
                            '_V0244_WARRIOR_ACTION_PREFIXES',
                            '_V0244_WARRIOR_LEVEL_TITLES',
                            '_V03014_SKILL_FAMILIES',
                            '_V03014_SKILL_TITLES',
                            '_V0922_CLASS_ALT_PROFILES',
                            '_V0922_MASTERY_LEVELS',
                            '_legacy_skill_unlock_to_mastery',
                            '_make_post200_mastery_skill',
                            '_make_soul_grid_skill',
                            '_v0244_warrior_alt_name',
                            '_v03014_skill_name_audit',
                            '_v03014_unique_generated_skill_names',
                            '_v0310_build_tech_class_skills',
                            '_v0310_tech_skill',
                            '_v0315_install_cosmic_rave',
                            '_v0317_install_engineer_toolkit',
                            '_v0319_install_full_mec_kit',
                            '_v0922_alt_skill',
                            'class_starting_stat_bonus',
                            'class_starting_stats_for',
                            'race_class_recommendation_text',
                            'starting_hp_mana_for',
                            'validate_complete_resource_atlases'),
 'player/session_mixins/class_guild_progress.py': ('SessionClassGuildProgressMixin',),
 'player/session_mixins/class_progression.py': ('SessionClassProgressionMixin',),
 'player/session_mixins/help_system.py': ('SessionHelpSystemMixin',),
 'player/session_mixins/party.py': ('SessionPartyMixin',),
 'player/session_mixins/progression_accessibility.py': ('SessionProgressionAccessibilityV03052Mixin',),
 'player/session_mixins/quest_commands.py': ('QuestCompletedEvent', 'SessionQuestCommandsMixin'),
 'player/session_mixins/quest_offers.py': ('SessionQuestOffersMixin',),
 'player/session_mixins/quest_progress.py': ('SessionQuestProgressMixin',),
 'player/session_mixins/skill_queue_buffs.py': ('SessionSkillQueueBuffsMixin',),
 'player/session_mixins/social_base.py': ('SessionBaseSocialMixin',),
 'player/session_mixins/social_expansion.py': ('SessionSocialExpansionMixin',),
 'player/session_mixins/world_events_endgame.py': ('SessionWorldEventsEndgameMixin',),
 'systems/dungeon_entry_commands.py': ('DUNGEON_ENTRY_SPECS_V03812',
                                              'DUNGEON_NAMED_ENTRY_AUDIT_V03812',
                                              'LATEST_CHANGES',
                                              'LATEST_CHANGES_TITLE',
                                              'V03812_DUNGEON_COMMANDS_VERSION',
                                              '_dungeon_exit_destination_before_v03812',
                                              '_dungeon_exit_destination_v03812',
                                              '_try_dungeon_entry_command_v03812',
                                              '_v03812_direction_to',
                                              '_v03812_norm',
                                              '_v03812_spec',
                                              '_v03812_specs_for_anchor',
                                              'dungeon_named_entry_audit_v03812'),
 'systems/full_systems_audit_v03062.py': ('FULL_SYSTEMS_AUDIT_V03062', 'full_systems_audit_v03062'),
 'systems/public_records.py': ('LATEST_CHANGES',
                                     'LATEST_CHANGES_TITLE',
                                     'PUBLIC_RECORDS_AUDIT_V0370',
                                     'V0370_VERSION',
                                     '_V0370_CHAR_XP_BEFORE',
                                     '_V0370_CLASS_XP_BEFORE',
                                     '_V0370_DB_INIT_BEFORE',
                                     '_V0370_GEM_DROP_BEFORE',
                                     '_V0370_MINE_BEFORE',
                                     '_V0370_MOB_PROGRESS_BEFORE',
                                     '_V0370_PERFORM_RECIPE_BEFORE',
                                     '_V0370_RECORDS_BEFORE',
                                     '_V0370_SALVAGE_BEFORE',
                                     '_V0370_SET_AUTO_MINING_BEFORE',
                                     '_V0370_SMELT_BEFORE',
                                     '_db_v0370_hof_first',
                                     '_db_v0370_record_max',
                                     '_db_v0370_record_row',
                                     '_v0370_char_xp',
                                     '_v0370_character_name',
                                     '_v0370_class_xp',
                                     '_v0370_craft_score',
                                     '_v0370_db_init',
                                     '_v0370_gem_drop',
                                     '_v0370_gem_score',
                                     '_v0370_key_salvage_outputs',
                                     '_v0370_mine',
                                     '_v0370_mob_progress',
                                     '_v0370_perform_recipe',
                                     '_v0370_records',
                                     '_v0370_salvage',
                                     '_v0370_seed_hall',
                                     '_v0370_set_auto_mining',
                                     '_v0370_smelt',
                                     'public_records_audit_v0370'),
 'systems/server_chronicle.py': ('LATEST_CHANGES',
                                        'LATEST_CHANGES_TITLE',
                                        'SERVER_CHRONICLE_AUDIT_V03811',
                                        'V03811_CHRONICLE_FILTERS',
                                        'V03811_CHRONICLE_LABELS',
                                        'V03811_SERVER_CHRONICLE_VERSION',
                                        '_V03811_DB_INIT_BEFORE',
                                        '_V03811_HELP_COMMANDS_BEFORE',
                                        '_db_v03811_add_event',
                                        '_db_v03811_claim_legend_key',
                                        '_db_v03811_record_exceptional_drop',
                                        '_db_v03811_record_fish',
                                        '_db_v03811_record_kill',
                                        '_db_v03811_record_project',
                                        '_db_v03811_rows',
                                        '_v03811_actor_phrase',
                                        '_v03811_db_init',
                                        '_v03811_help_commands',
                                        '_v03811_kill_importance',
                                        '_v03811_show_chronicle',
                                        '_v03811_world_boss',
                                        'server_chronicle_audit_v03811'),
 'world/expansions.py': ('REGIONAL_SET_BONUSES',
                         'TREASURE_CHESTS',
                         'TREASURE_CHEST_RARITIES',
                         'build_elite_rare_named_loot_expansion',
                         'build_forest_wolves_and_quest_balance',
                         'build_high_end_mob_pack',
                         'build_mountain_crafting_expansion',
                         'build_paid_training_guild_expansion',
                         'build_world_expansion_i',
                         'build_world_expansion_ii',
                         'configure_profession_tool_sellers',
                         'configure_v0800_help_info',
                         'configure_v081_help_info'),
 'world/party_combo_ultimate_summary.py': ('PARTY_COMBO_RULES_V0380',
                                                 'PARTY_COMBO_WINDOW_V0380',
                                                 'PARTY_SYSTEMS_AUDIT_V0380',
                                                 'PARTY_ULTIMATE_MAX_V0380',
                                                 '_add_character_xp_before_v0380',
                                                 '_add_character_xp_v0380',
                                                 '_create_party_before_v0380',
                                                 '_create_party_v0380',
                                                 '_disband_party_before_v0380',
                                                 '_disband_party_v0380',
                                                 '_dungeon_exit_before_v0380',
                                                 '_dungeon_exit_v0380',
                                                 '_grant_class_xp_before_v0380',
                                                 '_grant_class_xp_v0380',
                                                 '_grant_soul_xp_before_v0380',
                                                 '_grant_soul_xp_v0380',
                                                 '_handle_party_before_v0380',
                                                 '_handle_party_v0380',
                                                 '_leave_party_before_v0380',
                                                 '_leave_party_v0380',
                                                 '_mob_defeated_before_v0380',
                                                 '_mob_defeated_v0380',
                                                 '_move_before_v0380',
                                                 '_move_v0380',
                                                 '_realtime_player_action_before_v0380',
                                                 '_realtime_player_action_v0380',
                                                 '_record_item_collection_before_v0380',
                                                 '_record_item_collection_v0380',
                                                 '_revive_before_v0380',
                                                 '_revive_v0380',
                                                 '_show_party_before_v0380',
                                                 '_show_party_v0380',
                                                 '_use_class_skill_before_v0380',
                                                 '_use_class_skill_v0380',
                                                 '_v0380_add_ultimate',
                                                 '_v0380_crypt_identity',
                                                 '_v0380_finish_run',
                                                 '_v0380_local_party',
                                                 '_v0380_party_classes',
                                                 '_v0380_party_key',
                                                 '_v0380_run',
                                                 '_v0380_shared_target',
                                                 '_v0380_ultimate_state',
                                                 '_v0380_ultimate_store',
                                                 'party_systems_audit_v0380',
                                                 'party_ultimate_v0380')}
EXPLICIT_RUNTIME_EXPORTS.update(V045_EXPLICIT_RUNTIME_EXPORTS)
EXPLICIT_RUNTIME_EXPORTS["admin/explicit_stable_dependencies_audit_v0450.py"] = (
    "explicit_stable_dependencies_audit_v0450", "EXPLICIT_STABLE_DEPENDENCIES_AUDIT_V0450",
)

# v0.42.0 had 2385 implicit runtime-global references.  v0.43.0 moves a
# reviewed group out of that bridge and refuses any regression above this
# post-migration budget. v0.44.0 lowers it again after the second migration wave.


# v0.46.0: persistence layer no longer depends on compatibility-global injection.
V046_EXPLICIT_RUNTIME_EXPORTS = {
    "storage/db_accounts.py": ("DatabaseAccountsMixin",),
    "storage/db_world.py": ("DatabaseWorldMixin",),
    "storage/db_inventory.py": ("DatabaseInventoryMixin",),
    "storage/db_progression.py": ("DatabaseProgressionMixin",),
    "storage/db_quests.py": ("DatabaseQuestMixin",),
    "storage/db_guilds.py": ("DatabaseGuildMixin",),
    "storage/db_crafting_extensions.py": ("DatabaseCraftingExtensionsMixin",),
}
EXPLICIT_RUNTIME_EXPORTS.update(V046_EXPLICIT_RUNTIME_EXPORTS)
EXPLICIT_RUNTIME_EXPORTS["admin/explicit_persistence_audit_v0460.py"] = (
    "explicit_persistence_audit_v0460", "EXPLICIT_PERSISTENCE_AUDIT_V0460",
)

# v0.47.0: combat is split into focused explicit mixins. The old public
# SessionCombatMixin remains as a compatibility aggregate, but its implementation
# no longer depends on compatibility-global injection.
V047_EXPLICIT_RUNTIME_EXPORTS = {
    "player/session_mixins/combat_skills.py": ("SessionCombatSkillsMixin",),
    "player/session_mixins/combat_damage.py": ("SessionCombatDamageMixin",),
    "player/session_mixins/combat_realtime.py": ("SessionCombatRealtimeMixin",),
    "player/session_mixins/combat_rewards.py": ("party_drop_recipients_v0359", "SessionCombatRewardsMixin"),
    "player/session_mixins/combat_survival.py": ("SessionCombatSurvivalMixin",),
    "player/session_mixins/combat.py": ("SessionCombatMixin",),
}
EXPLICIT_RUNTIME_EXPORTS.update(V047_EXPLICIT_RUNTIME_EXPORTS)
EXPLICIT_RUNTIME_EXPORTS["admin/combat_architecture_audit_v0470.py"] = (
    "combat_architecture_audit_v0470", "COMBAT_ARCHITECTURE_AUDIT_V0470",
)

# v0.48.0: catalog ownership is guarded centrally; gameplay modules must use
# data.catalog_mutations instead of direct writes into shared runtime catalogs.
V048_EXPLICIT_RUNTIME_EXPORTS = {
    "admin/catalog_ownership_audit_v0480.py": (
        "catalog_ownership_audit_v0480", "CATALOG_OWNERSHIP_AUDIT_V0480",
    ),
}
EXPLICIT_RUNTIME_EXPORTS.update(V048_EXPLICIT_RUNTIME_EXPORTS)

# v0.49.0: command identity, alias provenance, handler routing and state-safety
# policy are centralized. The parser itself is now an explicit transport loop.
V049_EXPLICIT_RUNTIME_EXPORTS = {
    "core/command_catalog.py": (
        "COMMAND_LOOP_BREAK", "CommandDefinition", "CommandCatalog",
        "COMMAND_CATALOG", "CommandAliasMap", "COMMAND_CATALOG_VERSION",
    ),
    "player/session_mixins/command_special_handlers.py": ("SessionCommandSpecialHandlersMixin",),
    "player/session_mixins/command_loop.py": ("SessionCommandLoopMixin",),
    "admin/command_registry_audit_v0490.py": (
        "command_registry_audit_v0490", "COMMAND_REGISTRY_AUDIT_V0490",
    ),
}
EXPLICIT_RUNTIME_EXPORTS.update(V049_EXPLICIT_RUNTIME_EXPORTS)

# v0.50.0: stable historical gameplay layers use functional filenames and
# ordinary imports. Milestone numbers remain in symbol names/provenance only
# where they are part of the preserved compatibility API.
V050_EXPLICIT_RUNTIME_EXPORTS = {
    "network/tech_runes.py": ("_NEW_TECH_RUNES_V03111",),
    "systems/tech_crafting.py": (
        "TECH_COMPONENT_IDS", "_TECH_ITEMS", "TECH_CRAFT_RECIPES",
        "TECH_SALVAGE_RECIPES", "equipment_gem_socket_capacity_v03111",
    ),
    "systems/crafting_expansion.py": (
        "_REFINED", "RUNE_CRAFT_COSTS_V03114", "SALVAGE3_V03114",
        "TECH_SET_SPECS_V03114", "TECH_SET_SLOTS_V03114",
        "TECH_SET_SLOT_NAMES_V03114", "TECH_SET_ITEMS_V03114",
        "CRAFT_MATERIAL_STORAGE_IDS",
    ),
    "systems/milestone.py": (
        "TECH_SET_UPGRADE_COSTS_V0320", "room_is_dungeon_v0320",
        "dungeon_party_bonus_v0320",
    ),
    "systems/crafting_quality.py": (
        "CRAFT_QUALITY_V03054", "CRAFT_QUALITY_ORDER_V03054",
        "CRAFT_CRIT_AFFIXES_V03054", "CRAFT_CRIT_AFFIX_NAMES_V03054",
        "crafting_mastery_level_v03054", "crafting_mastery_category_v03054",
        "crafting_quality_roll_v03054", "crafting_critical_chance_v03054",
        "crafting_critical_affix_amount_v03054", "crafting_quality_variant_id_v03054",
        "_scale_int_v03054", "register_crafting_quality_variant_v03054",
        "parse_crafting_quality_variant_v0332", "ensure_crafting_quality_variant_v0332",
        "crafting_item_display_name_v0332", "player_item_display_name_v0335",
        "crafting_output_is_quality_equipment_v03054", "crafting_quality_output_v03054",
    ),
    "world/machine_expansion.py": (
        "MACHINE_ZONE", "MACHINE_BIO_IMMUNITIES", "_MACHINE_ITEMS",
        "_machine_template", "_MACHINE_MOBS", "_machine_rooms",
        "_MACHINE_SPAWNS", "v0314_machine_attack_element",
        "v0314_adjust_damage_vs_template",
    ),
    "world/magitek_dungeon.py": (
        "MAGITEK_DUNGEON_ZONE", "_v0319_rooms", "_v0319_mobs", "_v0319_spawns",
    ),
    "world/troll_shaman_density.py": (
        "_V03611_TROLL_SHAMAN_LAYOUT", "troll_shaman_density_audit_v03611",
        "TROLL_SHAMAN_DENSITY_AUDIT_V03611", "LATEST_CHANGES_TITLE", "LATEST_CHANGES",
    ),
    "systems/currency_ratio.py": (
        "V0385_CURRENCY_VERSION", "currency_ratio_audit_v0385", "CURRENCY_RATIO_AUDIT_V0385",
    ),
    "systems/smithing_materials.py": (
        "V03810_SMITHING_MATERIALS_VERSION", "v03810_upgrade_material_item_id",
        "smithing_materials_audit_v03810", "SMITHING_MATERIALS_AUDIT_V03810",
    ),
}
EXPLICIT_RUNTIME_EXPORTS.update(V050_EXPLICIT_RUNTIME_EXPORTS)
EXPLICIT_RUNTIME_EXPORTS["admin/maintainable_core_audit_v0500.py"] = (
    "maintainable_core_audit_v0500", "MAINTAINABLE_CORE_AUDIT_V0500",
)
EXPLICIT_RUNTIME_EXPORTS["admin/progression_pace_audit_v0501.py"] = (
    "progression_pace_audit_v0501", "PROGRESSION_PACE_AUDIT_V0501",
)
EXPLICIT_RUNTIME_EXPORTS["admin/long_term_balance_audit_v0502.py"] = (
    "long_term_balance_audit_v0502", "LONG_TERM_BALANCE_AUDIT_V0502",
)
EXPLICIT_RUNTIME_EXPORTS["world/world_expansion_i.py"] = (
    "WORLD_EXPANSION_I_VERSION", "WORLD_EXPANSION_I_SETTLEMENTS",
    "WORLD_EXPANSION_I_HUNTING_ZONES", "WORLD_EXPANSION_I_STATE",
)
EXPLICIT_RUNTIME_EXPORTS["admin/world_expansion_i_audit_v0510.py"] = (
    "world_expansion_i_audit_v0510", "WORLD_EXPANSION_I_AUDIT_V0510",
)

EXPLICIT_RUNTIME_EXPORTS["world/world_expansion_ii.py"] = (
    "WORLD_EXPANSION_II_VERSION", "WORLD_EXPANSION_II_CONTINENT",
    "WORLD_EXPANSION_II_CAPITAL", "WORLD_EXPANSION_II_VILLAGES",
    "WORLD_EXPANSION_II_HUNTING_ZONES", "WORLD_EXPANSION_II_STATE",
)
EXPLICIT_RUNTIME_EXPORTS["admin/world_expansion_ii_audit_v0520.py"] = (
    "world_expansion_ii_audit_v0520", "WORLD_EXPANSION_II_AUDIT_V0520",
)

EXPLICIT_RUNTIME_EXPORTS["world/living_npcs.py"] = (
    "V0560_VERSION", "V0560_HOURLY_COOLDOWN", "V0560_TAVERNS",
    "V0560_TAVERN_NPC_IDS", "V0560_TAVERN_QUEST_IDS",
    "V0560_GENERATED_HOURLY_IDS", "V0560_GENERATED_NPC_IDS",
    "V0560_ALL_HOURLY_IDS", "V0560_LIVING_NPCS_STATE",
    "ensure_hourly_quests_for_idle_npcs",
)
EXPLICIT_RUNTIME_EXPORTS["world/living_npcs_finalize.py"] = (
    "LIVING_NPCS_FINALIZE_STATE",
)
EXPLICIT_RUNTIME_EXPORTS["player/session_mixins/activity_guidance.py"] = (
    "SessionActivityGuidanceV0560Mixin",
)
EXPLICIT_RUNTIME_EXPORTS["admin/living_npcs_activity_audit_v0560.py"] = (
    "living_npcs_activity_audit_v0560", "LIVING_NPCS_ACTIVITY_AUDIT_V0560",
)
EXPLICIT_RUNTIME_EXPORTS["admin/living_npcs_late_finalize_audit_v0581.py"] = (
    "living_npcs_late_finalize_audit_v0581", "LIVING_NPCS_LATE_FINALIZE_AUDIT_V0581",
)

# v0.57.0: focused Courier and database-schema modularization.
EXPLICIT_RUNTIME_EXPORTS.update({
    "storage/schema_core.py": ("create_core_schema",),
    "storage/schema_progression.py": ("create_progression_schema",),
    "storage/schema_world_quests.py": ("create_world_quests_schema",),
    "storage/schema_social_guilds.py": ("create_social_guilds_schema",),
    "storage/schema_migrate_social.py": ("migrate_social_courier_schema",),
    "storage/schema_migrate_character.py": ("migrate_character_columns", "migrate_character_legacy"),
    "storage/schema_migrate_guilds.py": ("migrate_guild_schema",),
    "storage/schema_migrate_tools.py": ("migrate_stats_and_tools",),
    "storage/schema_migrate_economy.py": ("migrate_accounts_and_economy",),
    "storage/schema_migrate_history.py": ("migrate_history_and_collections",),
    "player/session_mixins/courier_delivery.py": ("SessionCourierDeliveryMixin",),
})
EXPLICIT_RUNTIME_EXPORTS["admin/modular_refactor_audit_v0570.py"] = (
    "modular_refactor_audit_v0570", "MODULAR_REFACTOR_AUDIT_V0570", "SCHEMA_MODULES_V0570",
)
EXPLICIT_RUNTIME_EXPORTS["player/session_mixins/progress_titles.py"] = (
    "SessionProgressTitlesV0580Mixin", "PROFESSIONS_V0580",
    "EXPLORATION_TITLES_V0580", "BOSS_TITLES_V0580",
    "PROFESSION_TITLE_THRESHOLDS_V0580",
)
EXPLICIT_RUNTIME_EXPORTS["player/session_mixins/progress_gaps.py"] = (
    "SessionProgressGapsV0590Mixin",
)
EXPLICIT_RUNTIME_EXPORTS["admin/titles_progress_audit_v0580.py"] = (
    "titles_progress_audit_v0580", "TITLES_PROGRESS_AUDIT_V0580",
)
EXPLICIT_RUNTIME_EXPORTS["admin/crafting_orders_compare_audit_v0600.py"] = (
    "crafting_orders_compare_audit_v0600", "CRAFTING_ORDERS_COMPARE_AUDIT_V0600",
)

EXPLICIT_RUNTIME_EXPORTS["admin/railway_packaging_audit_v0521.py"] = (
    "railway_packaging_audit_v0521", "RAILWAY_PACKAGING_AUDIT_V0521",
)
EXPLICIT_RUNTIME_EXPORTS["admin/postal_quest_rewards_audit_v0522.py"] = (
    "postal_quest_rewards_audit_v0522", "POSTAL_QUEST_REWARDS_AUDIT_V0522",
)
EXPLICIT_RUNTIME_EXPORTS["admin/courier_guild_audit_v0530.py"] = (
    "courier_guild_audit_v0530", "COURIER_GUILD_AUDIT_V0530",
)
EXPLICIT_RUNTIME_EXPORTS["admin/courier_achievements_audit_v0540.py"] = (
    "courier_achievements_audit_v0540", "COURIER_ACHIEVEMENTS_AUDIT_V0540",
)
EXPLICIT_RUNTIME_EXPORTS["admin/courier_prestige_tavern_audit_v0550.py"] = (
    "courier_prestige_tavern_audit_v0550", "COURIER_PRESTIGE_TAVERN_AUDIT_V0550",
)

LEGACY_IMPLICIT_DEPENDENCY_BUDGET = 1019

# v0.50.0: legacy compatibility is quarantined. A new runtime module may not
# silently enter the symbol-injection bridge; it must either be explicit or be
# deliberately reviewed and added to this allowlist.
LEGACY_COMPATIBILITY_ALLOWLIST = (
    'core/bootstrap_economy_professions.py',
    'core/progression_resources.py',
    'core/progression_600.py',
    'core/mines_threat.py',
    'systems/items_resources.py',
    'systems/content_registry.py',
    'world/economy_quests.py',
    'world/dynamic_content.py',
    'network/protocol_gameplay_utils.py',
    'world/generation_systems.py',
    'world/runtime_progression.py',
    'world/world_state.py',
    'systems/professions.py',
    'player/session_mixins/session_runtime_state.py',
    'player/session_mixins/rest_mana.py',
    'player/session_mixins/perception_maps.py',
    'player/session_mixins/collection_loot_records.py',
    'player/session_mixins/atlas_codex.py',
    'player/session_mixins/admin_tools.py',
    'player/session_mixins/quest_turnin.py',
    'player/session_mixins/forge_guilds.py',
    'player/session_mixins/tech_crafting.py',
    'player/session_mixins/milestone.py',
    'server/mud_server.py',
    'admin/help_refresh.py',
    'admin/audits.py',
    'systems/economy_audit_v03060.py',
    'world/uoss_superbosses.py',
    'world/crypt_party_rebalance.py',
    'world/crypt_floor_progression.py',
    'world/crypt_overdrive.py',
    'world/tower_overdrive.py',
    'world/magitek_infinite.py',
    'world/magitek_hourly_quests.py',
    'world/world_threat_overdrive.py',
    'admin/party_revive_audit_v0371.py',
    'world/global_difficulty_overdrive.py',
    'admin/bounty_target_audit_v0387.py',
    'admin/soul_tier8_trial_audit_v0388.py',
    'admin/quest_kill_credit_audit_v0389.py',
    'admin/bounty_abandon_audit_v03814.py',
    'admin/architecture_audit_v0390.py',
    'admin/maintenance_audit_v0400.py',
    'admin/native_modules_audit_v0410.py',
    'admin/release_integrity_v0369.py',
)

EXPECTED_OVERRIDE_ORDER = {'_boss_floor_chest_spec': ['network/protocol_gameplay_utils.py', 'world/magitek_infinite.py'],
 '_dynamic_mythic_astral_boss_profile': ['world/economy_quests.py', 'world/uoss_superbosses.py'],
 '_infinite_mythic_boss_profile': ['world/economy_quests.py', 'world/uoss_superbosses.py'],
 'boss_floor_identity': ['world/economy_quests.py', 'world/magitek_infinite.py'],
 'boss_key_for_template': ['network/protocol_gameplay_utils.py', 'world/magitek_infinite.py'],
 'create_infinite_astral_floor_definition': ['world/economy_quests.py',
                                             'world/uoss_superbosses.py',
                                             'world/tower_overdrive.py'],
 'create_infinite_crypt_floor_definition': ['world/economy_quests.py',
                                            'world/uoss_superbosses.py',
                                            'world/crypt_party_rebalance.py'],
 'create_infinite_magitek_floor_definition': ['world/magitek_infinite.py',
                                              'world/magitek_hourly_quests.py'],
 'milestone_boss_name': ['world/economy_quests.py', 'world/uoss_superbosses.py'],
 'normalize_profession_name': ['core/bootstrap_economy_professions.py', 'systems/professions.py'],
 'v0100_instance_spec': ['world/dynamic_content.py', 'world/magitek_infinite.py'],
 'v0150_environment_bonus': ['world/generation_systems.py', 'world/generation_systems.py'],
 'v0190_apply_combat_template': ['core/progression_resources.py',
                                 'world/crypt_party_rebalance.py',
                                 'world/crypt_floor_progression.py',
                                 'world/crypt_overdrive.py',
                                 'world/tower_overdrive.py',
                                 'world/global_difficulty_overdrive.py'],
 'v0190_combat_reward': ['core/progression_resources.py',
                         'world/crypt_party_rebalance.py',
                         'world/crypt_floor_progression.py',
                         'world/crypt_overdrive.py',
                         'world/tower_overdrive.py',
                         'world/global_difficulty_overdrive.py'],
 'v0927_guild_building_upgrade_cost': ['network/protocol_gameplay_utils.py', 'systems/economy_audit_v03060.py'],
 'v0927_guild_hall_upgrade_cost': ['network/protocol_gameplay_utils.py', 'systems/economy_audit_v03060.py']}


# Session method duplicates that are intentional compatibility layers. Any new
# duplicate method name across Session*Mixin classes is treated as a structural
# regression by the runtime loader.
EXPECTED_SESSION_METHOD_DUPLICATES = {
    "channel_broadcast_v03050": [
        "player/session_mixins/social_base.py:SessionBaseSocialMixin",
        "player/session_mixins/social_expansion.py:SessionSocialExpansionMixin",
    ],
    "show_channels_v03050": [
        "player/session_mixins/social_base.py:SessionBaseSocialMixin",
        "player/session_mixins/social_expansion.py:SessionSocialExpansionMixin",
    ],
    "tell": [
        "player/session_mixins/social_base.py:SessionBaseSocialMixin",
        "player/session_mixins/social_expansion.py:SessionSocialExpansionMixin",
    ],
    "who": [
        "player/session_mixins/social_base.py:SessionBaseSocialMixin",
        "player/session_mixins/social_expansion.py:SessionSocialExpansionMixin",
    ],
    "salvage_equipment_v0925": [
        "player/session_mixins/forge_guilds.py:SessionForgeGuildsMixin",
        "player/session_mixins/crafting_expansion.py:SessionCraftingExpansionV03114Mixin",
    ],
    "handle_mail_v03051": [
        "player/session_mixins/mail_attachments.py:SessionMailAttachmentsV0614Mixin",
        "player/session_mixins/social_expansion.py:SessionSocialExpansionMixin",
    ],
}

# v0.60.0: rotating NPC crafting orders and inventory-wide EQ comparison.
EXPLICIT_RUNTIME_EXPORTS["player/session_mixins/crafting_orders.py"] = (
    "CRAFTING_ORDER_REFRESH_SECONDS_V0600", "CRAFTING_ORDER_NPCS_V0600",
    "SessionCraftingOrdersV0600Mixin",
)
EXPLICIT_RUNTIME_EXPORTS["player/session_mixins/equipment_compare.py"] = (
    "SessionEquipmentCompareV0600Mixin",
)

EXPLICIT_RUNTIME_EXPORTS["player/session_mixins/mail_attachments.py"] = (
    "SessionMailAttachmentsV0614Mixin",
)
EXPLICIT_RUNTIME_EXPORTS["player/session_mixins/item_sources.py"] = (
    "V0610_ITEM_SOURCE_VERSION", "resolve_item_query_v0610", "item_source_entries_v0610",
    "SessionItemSourcesV0610Mixin",
)
EXPLICIT_RUNTIME_EXPORTS["admin/item_sources_party_coordination_audit_v0610.py"] = (
    "item_sources_party_coordination_audit_v0610", "ITEM_SOURCES_PARTY_COORDINATION_AUDIT_V0610",
    "memory_efficiency_audit_v0612", "V0612_MEMORY_EFFICIENCY_AUDIT",
)
EXPLICIT_RUNTIME_EXPORTS["admin/crafting_logistics_audit_v0614.py"] = (
    "V0614_CRAFTING_LOGISTICS_VERSION",
    "crafting_logistics_audit_v0614",
    "CRAFTING_LOGISTICS_AUDIT_V0614",
)


EXPLICIT_RUNTIME_EXPORTS["systems/runtime_memory.py"] = (
    "V0616_MEMORY_EFFICIENCY_VERSION",
    "compact_runtime_memory_v0616",
    "memory_efficiency_ii_audit_v0616",
    "V0616_MEMORY_EFFICIENCY_AUDIT",
)
